### ISSUE TITLE
Initial login after install using php 7

### ISSUE THREAD

**Issue by ggoun** [asipto/siremis-php#12]
I struggled to get to this point, I am on Ubuntu 16.10 and I am getting the following error after selecting all options on the "Database Configuration page"

ERROR: SQLSTATE[HY000] [1045] Access denied for user 'siremis'@'localhost' (using password: YES)

If there is a solution, please include step by step instructions as I am a novice at command line computing.

**Comment by imcdona** [comment]
That error indicates that SIREMIS is unable to login to the MySQL server due to an authentication issue.

Verify that user "siremis" exists on your mysql server, is allowed to use the siremis database and is allowed to login from localhost. Also verify the password you entered on the database configuration page is the same password you used when you created user "siremis".

**Comment by miconda** [comment]
Thanks @imcdona for helping with this. It is indeed a mysql access issue.
