### ISSUE TITLE
~/siremis/system/general_default - page not found

### ISSUE THREAD

**Issue by munishmahajan** [asipto/siremis-php#53]
Installed Siremis successfully but getting error ~/siremis/system/general_default - page not found.
a2enmod rewrite, prepare24 commands does not generate ~/siremis/system folder. How this folder is created? Could not find anything in Makefile when this folder is created. Any pointers to debug are highly appreciated.

**Comment by miconda** [comment]
It seems that the `a2enmod rewrite` didn't work for some reason, did you restart apache server?

The `system` folder doesn't need to be created, it is a module of siremis which is accessible by rewrite rules.

**Comment by munishmahajan** [comment]
I restarted apache but i think that i didn't executed a2enmod from siremis folder. My feeling is that a2enmod should be executed from siremis folder. Pl. correct me if i am wrong.

**Comment by munishmahajan** [comment]
do you think Php 7.4 could be any reason related to this since there was a deprecated error message (get_magic_quotes_gpc()) so i commented that if condition.

**Comment by munishmahajan** [comment]
one more point. git clone install /var/www/html/siremis/siremis
/var/www/html/siremis has Makefile and all Php, Js, Images etc are in /var/www/html/siremis/siremis.
Url - http://localhost/siremis/siremis/usr/login was not showing proper login page. After Debugging i found that page was loading Js, Images from /var/www/html/siremis But Not from /var/www/html/siremis/siremis so i copied all Js, Images etc folder in /var/www/html/siremis

**Comment by miconda** [comment]
Maybe it is easier for you to use docker, see:
  * https://github.com/asipto/siremis/tree/master/misc/docker

If not, try to do a fresh install following the guidelines at:

  * http://kb.asipto.com/siremis:install53x:main

Recommended OS is Debian stable.

**Comment by nmigliaro** [comment]
Hello,

I have just installed siremis using the http://kb.asipto.com/siremis:install53x:main. I have completed the "Web Installation Wizard" but everytime I try to log in using admin/admin (or other user) I get the error listed below.

Is it possible that is caused by the version of the php installed (7.4) which from what I understand, the function get_magic_quotes_gpc() is deprecated?

Many thanks in advance

-----------------------------------------------------------------------------------------------------------------------------------------
[{"target":"ERROR","content":"
\n[2022-08-21 22:24:04 (GMT)] An exception occurred while executing this script:
\nError message: #8192, Function get_magic_quotes_gpc() is deprecated<\/font>
\nScript name and line number of error: \/var\/www\/siremis-5.3.0\/openbiz\/bin\/ClientProxy.php:190<\/font>
\n

function:<\/b> errorHandler ( 8192, \"Function get_magic_quotes_gpc() is deprecated\", \"\/var\/www\/siremis-5.3.0\/openbiz\/bin\/ClientProxy.php\", 190, Array(3) ) @ \/var\/www\/siremis-5.3.0\/openbiz\/bin\/sysheader.inc 117\n
function:<\/b> userErrorHandler ( 8192, \"Function get_magic_quotes_gpc() is deprecated\", \"\/var\/www\/siremis-5.3.0\/openbiz\/bin\/ClientProxy.php\", 190, Array(3) ) @ \/var\/www\/siremis-5.3.0\/openbiz\/bin\/ClientProxy.php 190\n
function:<\/b> getFormInputs ( \"username\" ) @ \/var\/www\/siremis-5.3.0\/openbiz\/bin\/easy\/EasyForm.php 1401\n
function:<\/b> readInputRecord ( ) @ \/var\/www\/siremis-5.3.0\/siremis\/modules\/user\/form\/LoginForm.php 73\n
function:<\/b> Login ( ) @ \/var\/www\/siremis-5.3.0\/openbiz\/bin\/BizController.php 310\n
function:<\/b> invoke ( ) @ \/var\/www\/siremis-5.3.0\/openbiz\/bin\/BizController.php 110\n
function:<\/b> dispatchRequest ( ) @ \/var\/www\/siremis-5.3.0\/openbiz\/bin\/BizController.php 32\n
function:<\/b> include_once ( \"\/var\/www\/siremis-5.3.0\/openbiz\/bin\/BizController.php\" ) @ \/var\/www\/siremis-5.3.0\/siremis\/bin\/controller.php 6<\/div>\n
Please ask system administrator for help...<\/div>\n"}]
-----------------------------------------------------------------------------------------------------------------------------------------

root@SBC:/var/www# apt-cache show php
Package: php
Source: php-defaults (76)
Version: 2:7.4+76
Installed-Size: 13
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Architecture: all
Depends: php7.4
Description-en: server-side, HTML-embedded scripting language (default)
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
 .
 This package is a dependency package, which depends on latest stable
 PHP version (currently 7.4).
Description-md5: 99c58fa41ae5c5908fd17241a53bfdd9
Section: php
Priority: optional
Filename: pool/main/p/php-defaults/php_7.4+76_all.deb
Size: 6340
MD5sum: 33859926f35bdfdc784d9e7312d16a92
SHA256: 10ca22712771dc343fb6600cbdbc88069069467fcc5c85782ee89abbc8c81f59

root@SBC:/var/www#
root@SBC:/var/www# php -v
PHP 7.4.30 (cli) (built: Jul  7 2022 15:51:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
root@SBC:/var/www#
